In [1]:
import numpy as np

## Overview

We're modelling particle counts at $k$ detectors, caused by an event in a space X, discretized as $X^k$.

We assume that we can model a count at a detector $d_i$ as a Poisson distribution,

$$
d_i \sim Poisson(\theta_i \cdot x^k)
$$

where:
* the $x^k$ vectors are sparse; they correspond to a point event
* the structure of $\theta_i$ is not clear

In [2]:
class Sim:
    def __init__(self, theta):
        self.theta = theta
    
    def sample(self):
        n = self.theta.shape[0]
        
        x = np.random.multinomial(1, np.ones(n) / n)
        
        lam = np.dot(x, self.theta)
        
        y = np.random.poisson(lam)
        return x, y

In [6]:
sim = Sim(np.ones((4, 3)))
for i in range(10):
    print(sim.sample())

(array([1, 0, 0, 0]), array([0, 1, 2]))
(array([1, 0, 0, 0]), array([1, 1, 0]))
(array([0, 0, 0, 1]), array([0, 1, 2]))
(array([1, 0, 0, 0]), array([2, 1, 1]))
(array([1, 0, 0, 0]), array([2, 1, 2]))
(array([0, 1, 0, 0]), array([1, 1, 1]))
(array([0, 1, 0, 0]), array([0, 1, 0]))
(array([0, 0, 1, 0]), array([1, 0, 0]))
(array([0, 0, 0, 1]), array([1, 0, 3]))
(array([0, 1, 0, 0]), array([0, 1, 1]))
